"use client";
import {useState,useRef} from 'react';
export default function Console(){
 const [token,setToken]=useState(''),[subject,setSubject]=useState(''),[query,setQuery]=useState(''),[kind,setKind]=useState(''),[items,setItems]=useState([]),[cursor,setCursor]=useState(null),[selected,setSelected]=useState(null),[history,setHistory]=useState([]),[sources,setSources]=useState([]),[audit,setAudit]=useState([]),[status,setStatus]=useState('Connect to inspect memory.'),[busy,setBusy]=useState(false),[erasure,setErasure]=useState(null),[correction,setCorrection]=useState(''),[episode,setEpisode]=useState(''),[jobID,setJobID]=useState(''),[job,setJob]=useState(null);
 const dialog=useRef(null),opener=useRef(null),running=useRef(false);
 function clearView(){setItems([]);setCursor(null);setSelected(null);setHistory([]);setSources([]);setAudit([]);setErasure(null);setCorrection('');setEpisode('');setJob(null);setStatus('Connection changed. Search to load authorized memory.');}
 async function api(path,method='GET',body){
  const response=await fetch('/api/proxy',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({path,method,body})});
  const data=await response.json();if(!response.ok)throw Error(`${data.error?.code||'request_failed'}${data.error?.request_id?' · Request '+data.error.request_id:''}`);return data;
 }
 async function run(action){if(running.current)return;running.current=true;setBusy(true);try{await action()}catch(error){setStatus(error.message)}finally{running.current=false;setBusy(false)}}
 async function load(next=false){
  const params=new URLSearchParams({subject_id:subject,limit:'20'});if(query)params.set('q',query);if(kind&&!query)params.set('kind',kind);if(next&&cursor&&!query)params.set('cursor',cursor);
  const data=await api('/v1/'+(query?'search':'memories')+'?'+params);setItems(next?[...items,...data.items]:data.items);setCursor(data.next_cursor);setStatus(`${data.items.length} memories loaded${query&&kind?' · Kind filtering applies to browse only':''}.`);
 }
 async function inspect(memory){setSelected(memory);setCorrection(memory.content);setEpisode(memory.source_episode_ids[0]||'');setHistory([]);setSources([]);setAudit([]);setErasure(null);
  const data=await api(`/v1/memories/${memory.id}/history`);setHistory(data.versions);
  const events=await api(`/v1/memories/${memory.id}/audit`);setAudit(events.events);setStatus('Memory detail loaded.');
 }
 async function refreshStatus(){const data=await api(`/v1/memories/${selected.id}/erasure`);setErasure(data.erasure);setStatus('Erasure status refreshed.');}
 return <main><header><a href="#content" className="skip">Skip to memories</a><div className="brand"><span className="mark">m</span><div>MEMORY SYSTEM<small>Operator workspace</small></div></div><span className="badge">Private · Subject scoped</span></header>
 <section className="intro"><span className="eyebrow">THE MEMORY LAYER</span><h1>Keep context.<br/><span>Keep control.</span></h1><p>Inspect what your agent remembers, trace its sources, and make every correction accountable.</p></section>
 <section className="connection" aria-label="Connection"><label>Access token<input disabled={busy} type="password" autoComplete="off" value={token} onChange={e=>{clearView();setToken(e.target.value)}} placeholder="Paste an expiring bearer token"/></label><label>Subject ID<input disabled={busy} value={subject} onChange={e=>{clearView();setSubject(e.target.value)}} placeholder="Subject UUID"/></label><p>Credentials stay in this tab’s memory. Closing or reloading clears them.</p></section>
 <div role="status" aria-live="polite" className="status">{busy?'Working…':status}</div>
 <section id="content" className="workspace"><div className="collection"><div className="sectionhead"><h2>Memory library</h2><span>{items.length} loaded</span></div>
 <form className="search" onSubmit={e=>{e.preventDefault();run(()=>load())}}><label>Search<input disabled={busy} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search remembered facts"/></label><label>Kind<select value={kind} disabled={busy||!!query} onChange={e=>setKind(e.target.value)}><option value="">All kinds</option>{['core','profile','session','temporal'].map(k=><option key={k}>{k}</option>)}</select></label><button disabled={busy||!token||!subject}>Search memories</button></form>
 <div className="cards">{items.map(memory=><button disabled={busy} className="card" key={memory.id} onClick={()=>run(()=>inspect(memory))}><span className="tag">{memory.kind} · {memory.origin}</span><strong>{memory.content}</strong><span>{Math.round(memory.confidence*100)}% confidence · {memory.source_episode_ids.length} sources</span></button>)}{!items.length&&<div className="empty"><span>◇</span><h3>Your agent’s context, in view.</h3><p>Connect a subject and search to inspect its memories.</p></div>}</div>{cursor&&!query&&<button className="secondary" onClick={()=>run(()=>load(true))} disabled={busy}>Load more</button>}
 </div><aside aria-label="Memory detail"><h2>Memory detail</h2>{selected?<><span className="tag">{selected.kind} · {selected.origin}</span><p className="detailtext">{erasure?'This memory is suppressed.':selected.content}</p><dl><dt>Memory ID</dt><dd>{selected.id}</dd><dt>Version ID</dt><dd>{selected.version_id}</dd><dt>Indexing</dt><dd>{selected.indexing_state}</dd><dt>Importance</dt><dd>{selected.importance}</dd></dl>
 <h3>Version history</h3><ol>{history.map(v=><li key={v.id}><strong>{v.content||'Content suppressed'}</strong><small>{v.origin} · {v.valid_to?'Superseded':'Current'} · {new Date(v.valid_from).toLocaleString()}</small></li>)}</ol>
 {!erasure&&<><button className="secondary" disabled={busy} onClick={()=>run(async()=>{const data=await api(`/v1/memories/${selected.id}/sources`);setSources(data.episodes);setStatus('Source evidence loaded.')} )}>Inspect source evidence</button>{sources.map(s=><div className="evidence" key={s.id}><small>{s.id}</small>{s.messages.map((m,i)=><p key={i}><b>{m.role}: </b>{m.content}</p>)}</div>)}
 <h3>Correct memory</h3><form onSubmit={e=>{e.preventDefault();run(async()=>{const data=await api(`/v1/memories/${selected.id}`,'PATCH',{expected_version_id:selected.version_id,content:correction,source:{episode_id:episode},confidence:selected.confidence,importance:selected.importance});await inspect(data.memory);await load();setStatus('Correction saved as a new version.');})}}><label>Corrected content<textarea required value={correction} onChange={e=>setCorrection(e.target.value)}/></label><label>Supporting episode ID<input required value={episode} onChange={e=>setEpisode(e.target.value)}/></label><button disabled={busy}>Save correction</button></form>
 <button className="danger" disabled={busy} onClick={e=>{opener.current=e.currentTarget;dialog.current.showModal()}}>Forget memory</button></>}
 {erasure&&<section><h3>Erasure status</h3><p>{erasure.state} · Shared episodes retained: {erasure.retained_shared_episodes}</p><button className="secondary" onClick={()=>run(refreshStatus)} disabled={busy}>Refresh erasure status</button>{erasure.state==='blocked'&&<button disabled={busy} onClick={()=>{opener.current=null;dialog.current.showModal()}}>Authorize erasure retry</button>}</section>}
 <h3>Recent audit events</h3><ul>{audit.map(a=><li key={a.id}><b>{a.action}</b><small>{a.outcome} · {new Date(a.created_at).toLocaleString()} · Request {a.request_id}</small></li>)}</ul>
 </>:<div className="empty detail"><span>↗</span><p>Select a memory to view its evidence and controls.</p></div>}</aside></section>
 <section className="job"><h2>Formation job status</h2><form onSubmit={e=>{e.preventDefault();run(async()=>{const data=await api('/v1/jobs/'+jobID);setJob(data.job);setStatus('Job status loaded.')})}}><label>Job ID<input value={jobID} onChange={e=>setJobID(e.target.value)} placeholder="Job UUID" required/></label><button disabled={busy||!token}>Check job</button></form>{job&&<p>{job.state} · {job.attempts} attempts{job.error_code?' · '+job.error_code:''}</p>}</section>
 <dialog ref={dialog} onClose={()=>opener.current?.focus()}><h2>{erasure?'Authorize erasure retry?':'Forget this memory?'}</h2><p>Retrieval stops immediately. Structured content and unshared episode content will be erased after the configured retention period. Shared episode evidence may remain.</p><div className="actions"><button autoFocus className="secondary" onClick={()=>dialog.current.close()}>Cancel</button><button className="danger" disabled={busy} onClick={()=>run(async()=>{const data=await api(`/v1/memories/${selected.id}/`+(erasure?'erasure/retry':'forget'),'POST',{confirm:true,expected_version_id:selected.version_id});setErasure(data.erasure);setItems(items.filter(m=>m.id!==selected.id));setSelected({...selected,content:''});setHistory([]);setSources([]);setCorrection('');setEpisode('');setAudit([]);dialog.current.close();await load();const events=await api(`/v1/memories/${selected.id}/audit`);setAudit(events.events);setStatus('Memory suppressed. Erasure queued.');})}>{erasure?'Confirm erasure retry':'Confirm forget'}</button></div></dialog>
 <footer>Memory System <span>Evidence first. Every change traceable.</span></footer></main>
}
